"""initial schema

Revision ID: bc84352880ab
Revises: 
Create Date: 2026-06-27 22:29:06.974703+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc84352880ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('has_seen_onboarding', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('free_trial', 'creator', 'pro', name='plan_enum'), nullable=False),
    sa.Column('credits_total_this_period', sa.Integer(), nullable=False),
    sa.Column('credits_used_this_period', sa.Integer(), nullable=False),
    sa.Column('period_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_audit',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_admin_user_id'), 'admin_audit', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_occurred_at'), 'admin_audit', ['occurred_at'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('signup_grant', 'period_renewal', 'admin_grant', 'mock_purchase', 'generate_panel', 'generate_reference', 'generate_variant', 'generate_cover', 'adapt_script', 'generate_subject', 'refund', name='credit_operation_enum'), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_occurred_at'), 'credit_ledger', ['occurred_at'], unique=False)
    op.create_index('ix_ledger_user_time', 'credit_ledger', ['user_id', 'occurred_at'], unique=False)
    op.create_table('projects',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('length_target', sa.Enum('striscia', 'breve', 'medio', 'lungo', name='length_target_enum'), nullable=False),
    sa.Column('page_format', sa.String(length=16), nullable=False),
    sa.Column('style_id', sa.String(length=255), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'slug', name='uq_project_owner_slug')
    )
    op.create_index('ix_project_owner_updated', 'projects', ['owner_user_id', 'updated_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('character_sheets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('visual_description', sa.Text(), nullable=False),
    sa.Column('color_palette', sa.Text(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_charsheet_project_name')
    )
    op.create_index(op.f('ix_character_sheets_project_id'), 'character_sheets', ['project_id'], unique=False)
    op.create_table('covers',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('illustration_storage_key', sa.String(length=512), nullable=True),
    sa.Column('rendered_storage_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('page_layouts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('grid_id', sa.String(length=64), nullable=False),
    sa.Column('show_balloons', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'page_number', name='uq_pagelayout_project_page')
    )
    op.create_index(op.f('ix_page_layouts_project_id'), 'page_layouts', ['project_id'], unique=False)
    op.create_table('scripts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('logline', sa.Text(), nullable=False),
    sa.Column('n_pages', sa.Integer(), nullable=False),
    sa.Column('n_panels', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('usage_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_user_time', 'usage_log', ['user_id', 'occurred_at'], unique=False)
    op.create_table('vignettes',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('panel_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('aspect_ratio_key', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'page_number', 'panel_number', name='uq_vignette_p_p')
    )
    op.create_index('ix_vignette_project', 'vignettes', ['project_id'], unique=False)
    op.create_index(op.f('ix_vignettes_prompt_hash'), 'vignettes', ['prompt_hash'], unique=False)
    op.create_table('reference_images',
    sa.Column('character_sheet_id', sa.UUID(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('variant_kind', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_sheet_id'], ['character_sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_sheet_id', 'slot_number', name='uq_refimg_charsheet_slot')
    )
    op.create_index(op.f('ix_reference_images_character_sheet_id'), 'reference_images', ['character_sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_images_character_sheet_id'), table_name='reference_images')
    op.drop_table('reference_images')
    op.drop_index(op.f('ix_vignettes_prompt_hash'), table_name='vignettes')
    op.drop_index('ix_vignette_project', table_name='vignettes')
    op.drop_table('vignettes')
    op.drop_index('ix_usage_user_time', table_name='usage_log')
    op.drop_table('usage_log')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_page_layouts_project_id'), table_name='page_layouts')
    op.drop_table('page_layouts')
    op.drop_table('covers')
    op.drop_index(op.f('ix_character_sheets_project_id'), table_name='character_sheets')
    op.drop_table('character_sheets')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_project_owner_updated', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_ledger_user_time', table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_occurred_at'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_admin_audit_occurred_at'), table_name='admin_audit')
    op.drop_index(op.f('ix_admin_audit_admin_user_id'), table_name='admin_audit')
    op.drop_table('admin_audit')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
