// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/snaptoon/Genera.tsx": () => import("../components/mockups/snaptoon/Genera.tsx"),
  "./components/mockups/snaptoon/Home.tsx": () => import("../components/mockups/snaptoon/Home.tsx"),
  "./components/mockups/snaptoon/Login.tsx": () => import("../components/mockups/snaptoon/Login.tsx")
};
